name = "venehsoftw/swap_inicial"
version = "0.0.0"
compiler = "v1.1.19"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'venehsoftw/swap_inicial'"

[repository]
user = "venehsoftw"
project = "swap_inicial"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v3.0.0"
source = "github"

[config]
